import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Provider from "./sessionProvider";

const roboto = Roboto({ subsets: ["latin"], display: "swap", weight: "500" });

export const metadata: Metadata = {
  title: "Online Shop || Next.js",
  description: "Generated by create next app",
  icons: { icon: "/icon.png"}
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
